/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjtform;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author chandrag
 */
public class meet1 extends javax.swing.JFrame {

    /**
     * Creates new form meet1
     */
    public meet1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        off_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        meet_no = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        meet_name = new javax.swing.JTextField();
        first = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        zonal_no = new javax.swing.JTextField();
        second = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        off_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        exp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(695, 175, 63, 25);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(553, 381, 93, 25);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton6.setText("ADD");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(553, 338, 93, 25);

        off_id.setText("OFFICIAL'S ID");
        getContentPane().add(off_id);
        off_id.setBounds(43, 340, 252, 22);

        jLabel2.setText("OVERALL 1ST:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(142, 229, 84, 16);

        name.setText("PARTICIPANT CHEST NUMBER");
        getContentPane().add(name);
        name.setBounds(43, 489, 252, 22);

        jLabel6.setText("OVERALL 2ND:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(142, 269, 84, 16);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setText("REMOVE");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(553, 487, 93, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("MEET DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 10, 146, 39);
        getContentPane().add(meet_no);
        meet_no.setBounds(263, 62, 383, 31);

        jLabel3.setText("MEET NO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(168, 69, 58, 16);
        getContentPane().add(meet_name);
        meet_name.setBounds(263, 111, 383, 35);

        first.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COIMBATORE INSTITUTE OF TECHNOLOGY", "SRI ESHWAR COLLEGE OF TECHNOLOGY", "PSG COLLEGE OF TECHNOLOGY", "PSG COLLEGE OF APPLIED SCIENCE", "HINDUSTHAN COLLEGE OF TECHNOLOGY", "KONGU COLLEGE OF TECHNOLOGY", "BANNARI AMMAN INSTITUTE OF TECHNOLOGY", "SRI SAKTHI INSTITUTE OF ENGINEERING AND TECHNOLOGY", "KUMARAGURU COLLEGE OF TECHNOLOGY", "SRI SAKTHI COLLEGE OF TECHNOLOGY", "SRI KRISHNA COLLEGE OF TECHNOLOGY", "SRI RAMAKRISHNA COLLEGE OF TECHNOLOGY", "AKSHAYA COLLEGE OF TECHNOLOGY", "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY", "GOVERNMENT COLLEGE OF TECHNOLOGY", "KALAINAR KARUNANITHI INSITUTE OF TECHNOLOGYV", "COIMBATORE INSTITUTE OF ENGINEERING AND TECHNOLOGY", "Dr.NGP INSTITUTE OF TECHNOLOGY", "SNS COLLEGE OF TECHNOLOGY", "KARPAGAM INSTITUTE OF TECHNOLOGY", "PARK INSTITUTE OF TECHNOLOGY", "KATHIR COLLEGE OF TECHNOLOGY", "AISWARYA COLLEGE OF TECHNOLOGY", "NANDHA COLLEGE OF TECHNOLOGY", "MAHENDHIRA COLLEGE OF TECHNOLOGY" }));
        getContentPane().add(first);
        first.setBounds(263, 226, 383, 22);

        jLabel4.setText("ZONAL NO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(162, 180, 64, 16);
        getContentPane().add(zonal_no);
        zonal_no.setBounds(263, 173, 383, 30);

        second.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COIMBATORE INSTITUTE OF TECHNOLOGY", "SRI ESHWAR COLLEGE OF TECHNOLOGY", "PSG COLLEGE OF TECHNOLOGY", "PSG COLLEGE OF APPLIED SCIENCE", "HINDUSTHAN COLLEGE OF TECHNOLOGY", "KONGU COLLEGE OF TECHNOLOGY", "BANNARI AMMAN INSTITUTE OF TECHNOLOGY", "SRI SAKTHI INSTITUTE OF ENGINEERING AND TECHNOLOGY", "KUMARAGURU COLLEGE OF TECHNOLOGY", "SRI SAKTHI COLLEGE OF TECHNOLOGY", "SRI KRISHNA COLLEGE OF TECHNOLOGY", "SRI RAMAKRISHNA COLLEGE OF TECHNOLOGY", "AKSHAYA COLLEGE OF TECHNOLOGY", "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY", "GOVERNMENT COLLEGE OF TECHNOLOGY", "KALAINAR KARUNANITHI INSITUTE OF TECHNOLOGYV", "COIMBATORE INSTITUTE OF ENGINEERING AND TECHNOLOGY", "Dr.NGP INSTITUTE OF TECHNOLOGY", "SNS COLLEGE OF TECHNOLOGY", "KARPAGAM INSTITUTE OF TECHNOLOGY", "PARK INSTITUTE OF TECHNOLOGY", "KATHIR COLLEGE OF TECHNOLOGY", "AISWARYA COLLEGE OF TECHNOLOGY", "NANDHA COLLEGE OF TECHNOLOGY", "MAHENDHIRA COLLEGE OF TECHNOLOGY" }));
        getContentPane().add(second);
        second.setBounds(263, 266, 383, 22);

        jLabel5.setText("MEET NAME:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(152, 120, 74, 16);

        off_name.setText("OFFICIAL'S NAME");
        getContentPane().add(off_name);
        off_name.setBounds(43, 383, 252, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("REMOVE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(553, 424, 93, 25);

        exp.setText("EXPERIANCE");
        getContentPane().add(exp);
        exp.setBounds(43, 426, 252, 22);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setText("TO ENTER EVENT RESULTS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(292, 550, 225, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\chandrag\\Desktop\\bg3.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 780, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:dbms","kowreesh","kowree3801");
            String sql = "insert into meet values(?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(meet_no.getText()));
            ps.setInt(2, Integer.parseInt(zonal_no.getText()));
            ps.setString(3,meet_name.getText());
            String fst;
            fst=first.getSelectedItem().toString();
            ps.setString(4,fst);
            String sec;
            sec=second.getSelectedItem().toString();
            ps.setString(5,sec);
            ps.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null,"SUCCESSFULLY ADDED MEET DETAILS");
        }
        catch(Exception x)
        {
            //System.out.println(x);
            JOptionPane.showMessageDialog(null,x);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String qr="UPDATE OFFICIALS SET OFF_ID=?,OFF_Name=?,experiance=? where OFF_ID=?";
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:dbms","kowreesh","kowree3801");
            PreparedStatement ps = conn.prepareStatement(qr);
            ps.setInt(1,Integer.parseInt(off_id.getText()));
            ps.setString(2,off_name.getText());
            ps.setInt(3,Integer.parseInt(exp.getText()));
            ps.setInt(4,Integer.parseInt(off_id.getText()));
            ResultSet rs = ps.executeQuery();
            conn.close();
            JOptionPane.showMessageDialog(null,"SUCCESSFULLY UPDATED OFFICIAL NAME");
            rs.close();
        }
        catch(Exception x)
        {
            //System.out.println(x);
            JOptionPane.showMessageDialog(null,x);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String qr="insert into officials values ( "+this.off_id.getText()+", '"+off_name.getText()+"',"+this.exp.getText()+")";
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:dbms","kowreesh","kowree3801");
            PreparedStatement ps = conn.prepareStatement(qr);
            ResultSet rs = ps.executeQuery();
            conn.close();
            JOptionPane.showMessageDialog(null,"SUCCESSFULLY ADDED OFFICIAL NAME");
            rs.close();
        }
        catch(Exception x)
        {
            //System.out.println(x);
            JOptionPane.showMessageDialog(null,x);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String qr="DELETE FROM OFFICIALS WHERE OFF_ID= ?";
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:dbms","kowreesh","kowree3801");
            PreparedStatement ps = conn.prepareStatement(qr);
            ps.setInt(1,Integer.parseInt(off_id.getText()));
            //ps.setInt(2,Integer.parseInt(off_name.getText()));
            ResultSet rs = ps.executeQuery();
            conn.close();
            JOptionPane.showMessageDialog(null,"SUCCESSFULLY DELETED OFFICIAL NAME");
            rs.close();
        }
        catch(Exception x)
        {
            //System.out.println(x);
            JOptionPane.showMessageDialog(null,x);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String qr="DELETE FROM PARTICIPANTS WHERE CHEAT_NO= ?";
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:dbms","kowreesh","kowree3801");
            PreparedStatement ps = conn.prepareStatement(qr);
            ps.setInt(1,Integer.parseInt(name.getText()));
            ResultSet rs = ps.executeQuery();
            conn.close();
            JOptionPane.showMessageDialog(null,"SUCCESSFULLY DELETED PARTICIPANT'S DETAILS");
            rs.close();
        }
        catch(Exception x)
        {
            //System.out.println(x);
            JOptionPane.showMessageDialog(null,x);
        }    
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new result().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meet1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField exp;
    private javax.swing.JComboBox<String> first;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField meet_name;
    private javax.swing.JTextField meet_no;
    private javax.swing.JTextField name;
    private javax.swing.JTextField off_id;
    private javax.swing.JTextField off_name;
    private javax.swing.JComboBox<String> second;
    private javax.swing.JTextField zonal_no;
    // End of variables declaration//GEN-END:variables
}
